spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: SPOTIFY_CLIENT_ID
            client-secret: SPOTIFY_CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spotify
            scope:
              - user-read-private
              - user-read-email
              - user-read-playback-state
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:./data/database.db

hibernate:
  show_sql: true
  format_sql: true
  highlight_sql: true
